<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <Target Name="CreateAndBundleTestZip" BeforeTargets="BeforeBuild">

    <ZipDirectory SourceDirectory="Builder/mockZipContents" DestinationFile="Builder/mockZip.zip" Overwrite="true" />
    
  </Target>

  <ItemGroup>
	  <EmbeddedResource Include="Builder/mockZip.zip" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PMDDesktop.Server.Assets\PMDDesktop.Server.Assets.csproj" />
  </ItemGroup>

</Project>
